[project]
name = "operator-fusion-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kungpaugasol", email = "kungpaugasol@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["fusion", "bench"]
module-root = "src"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
